// Code generated by Slice Machine. DO NOT EDIT.

import Contact from './Contact';
import Hero from './Hero';
import Image from './Image';
import Menu from './Menu';
import NosServices from './NosServices';
import Slider from './Slider';

export {
	Contact,
	Hero,
	Image,
	Menu,
	NosServices,
	Slider,
};

export const components = {
	contact: Contact,
	hero: Hero,
	image: Image,
	menu: Menu,
	nos_services: NosServices,
	slider: Slider,
};
