// Code generated by Slice Machine. DO NOT EDIT.

import Contact from './Contact';
import Hero from './Hero';

export {
	Contact,
	Hero,
};

export const components = {
	contact: Contact,
	hero: Hero,
};
